config/routes.rb
Workaholic::Application.routes.draw do
  resources :offs

  resources :overworks

  devise_for :users
  get "welcome/index"

  root 'welcome#index'

end

app/models/boss.rb
class Boss < ActiveRecord::Base
  belongs_to :user
  #belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :boss, class_name: 'User', foreign_key: :boss_id
end

app/models/off.rb
class Off < ActiveRecord::Base
  belongs_to :user
end

app/models/overwork.rb
class Overwork < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boss_links, class_name: 'Boss', foreign_key: :user_id, dependent: :destroy
  has_many :bosses, through: :boss_links, source: :boss

  has_many :buka_links, class_name: 'Boss', foreign_key: :boss_id, dependent: :destroy
  has_many :bukas, through: :buka_links, source: :user

  has_many :overworks
  has_many :offs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/offs_controller.rb
# -*- coding: utf-8 -*-
class OffsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_off, only: [:show, :edit, :update, :destroy]

  # GET /offs
  # GET /offs.json
  def index
    @fy = params[:fy] ? params[:fy].to_i : to_fy(Date.today)
    @offs = current_user.offs.where(fy:@fy).order(:off_date)

    @offs0 = @offs.where(off_type:0).order(:off_date)
    @offs1 = @offs.where(off_type:1).order(:off_date)
    @offs2 = @offs.where(off_type:2).order(:off_date)

  end

  # GET /offs/1
  # GET /offs/1.json
  def show
  end

  # GET /offs/new
  def new
    @off = current_user.offs.new
    @off.subject = '私用'
  end

  # GET /offs/1/edit
  def edit
  end

  # POST /offs
  # POST /offs.json
  def create
    @off = current_user.offs.new(off_params)
    calc_off

    respond_to do |format|
      if @off.save
        format.html { redirect_to offs_url, notice: 'Off was successfully created.' }
        format.json { render action: 'show', status: :created, location: @off }
      else
        format.html { render action: 'new' }
        format.json { render json: @off.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offs/1
  # PATCH/PUT /offs/1.json
  def update
    @off.assign_attributes(off_params)
    calc_off

    respond_to do |format|
      if @off.save
        format.html { redirect_to offs_url, notice: 'Off was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @off.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offs/1
  # DELETE /offs/1.json
  def destroy
    @off.destroy
    respond_to do |format|
      format.html { redirect_to offs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_off
      @off = Off.find(params[:id])
      @off = nil if @off.user_id != current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def off_params
      params.require(:off).permit(:off_date, :subject, :off_type, :off_half_type, :off_quarter_time)
    end

  # helper
  def to_fy(date)
    date.year - (date.month < 4 ? 1 : 0)
  end

  def calc_off
    @off.off_days = 1.0 / (2**@off.off_type)
    @off.off_half_type = nil unless @off.off_type == 1
    @off.off_quarter_time = nil unless @off.off_type == 2
    @off.fy = to_fy(@off.off_date)
    @off
  end
end

app/controllers/overworks_controller.rb
# -*- coding: utf-8 -*-
class OverworksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_overwork, only: [:show, :edit, :update, :destroy]

  # GET /overworks
  # GET /overworks.json
  def index
    shimebi = 20
    today = Date.today
    if params[:me]
      @me = Date.new(*(params[:me]+shimebi.to_s).unpack('a4a2a2').map(&:to_i))
    else
      @me = Date.new(today.year, today.month, shimebi)
      @me += 1.month if today.day > shimebi
    end
    @ms = @me - 1.month + 1.day

    #@overworks = current_user.overworks
    overworks = Overwork.where(user_id: current_user.id, work_date: @ms..@me).order(:work_date)
    @total = overworks.sum :work_hours

    ak = (@ms..@me).to_a
    av = Array.new(ak.size, nil)
    @overworks = Hash[*[ak,av].transpose.flatten]
    #logger.error @overworks
    overworks.each do |overwork|
      @overworks[overwork.work_date] = overwork
    end

  end

  # GET /overworks/1
  # GET /overworks/1.json
  def show
  end

  # GET /overworks/new
  def new
    @work_date = params[:work_date] ? Date.parse(params[:work_date]) : Date.today
    @overwork = Overwork.where(user_id: current_user.id, work_date: @work_date).first
    redirect_to edit_overwork_path @overwork if @overwork

    @overwork = current_user.overworks.new
    @overwork.work_date = @work_date
    @overwork.work_start_time = Time.new(0)+18*3600
    @overwork.work_finish_time = Time.new(0)+Time.now.hour*3600
  end

  # GET /overworks/1/edit
  def edit
  end

  # POST /overworks
  # POST /overworks.json
  def create
    #@overwork = Overwork.new(overwork_params)
    @overwork = current_user.overworks.new(overwork_params)
    @overwork.work_hours = (@overwork.work_finish_time - @overwork.work_start_time)/3600
    respond_to do |format|
      if @overwork.save
        format.html { redirect_to overworks_path, notice: 'Overwork was successfully created.' }
        format.json { render action: 'show', status: :created, location: @overwork }
      else
        format.html { render action: 'new' }
        format.json { render json: @overwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /overworks/1
  # PATCH/PUT /overworks/1.json
  def update
    respond_to do |format|
      @overwork.assign_attributes(overwork_update_params)
      @overwork.work_hours = (@overwork.work_finish_time - @overwork.work_start_time)/3600
      OverworkMailer.create('残業申請（結果） '+@overwork.work_date.strftime('%Y/%m/%d'), @overwork).deliver
      if @overwork.save
        format.html { redirect_to overworks_path, notice: 'Overwork was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @overwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overworks/1
  # DELETE /overworks/1.json
  def destroy
    @overwork.destroy
    respond_to do |format|
      format.html { redirect_to overworks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_overwork
      @overwork = Overwork.find(params[:id])
      @overwork = nil if @overwork.user_id != current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def overwork_params
    params.require(:overwork).permit(:work_date, :subject, :work_start_time, :work_finish_time, :comment)
  end
  def overwork_update_params
    params.require(:overwork).permit(:subject, :work_start_time, :work_finish_time, :comment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  WDAYS = ["日", "月", "火", "水", "木", "金", "土"]
  def yo day
    WDAYS[day.wday]
  end
end

app/helpers/offs_helper.rb
module OffsHelper
end

app/helpers/overworks_helper.rb
module OverworksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Workaholic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <%= link_to 'Workaholic', :root, {class: 'navbar-brand'} %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to '残業申請', new_overwork_path %></li>
      <li><%= link_to '残業一覧', overworks_path %></li>
      <li><%= link_to '休暇申請', new_off_path %></li>
      <li><%= link_to '休暇一覧', offs_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div class="container">
<!--
  <p id="notice" class="notice"><%= notice %></p>
  <p id="alert" class="alert"><%= alert %></p>
-->
  <%= yield %>
</div>
<!--
<%= debug(params) if Rails.env.development? %>
-->
</body>
</html>

app/views/offs/_form.html.erb
<%= form_for(@off) do |f| %>
  <% if @off.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@off.errors.count, "error") %> prohibited this off from being saved:</h2>

      <ul>
      <% @off.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :off_date %><br>
    <%= f.text_field :off_date, {'data-behaviour'=>'datepicker'} %>
  </div>
  <script type="text/javascript">
      $(document).ready(function(){
          $('[data-behaviour~=datepicker]').datepicker({
              language: "ja",
              todayBtn: true,
              autoclose: true,
              todayHighlight: true
          });
      })
  </script>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <table>
    <tbody class="field">
    <tr>
      <td><%= f.radio_button :off_type, 0 %>休暇</td>
    </tr>
    <tr>
      <td><%= f.radio_button :off_type, 1 %>半休</td>
      <td class="field">
        <%= f.radio_button :off_half_type, 1 %>午前
        <%= f.radio_button :off_half_type, 2 %>午後
      </td>
    </tr>
    <tr>
      <td><%= f.radio_button :off_type, 2 %>２時間休</td>
      <td class="field">
        <%= f.time_select :off_quarter_time, include_blank:true, start_hour:9, end_hour:16, minute_step:15 %>
      </td>
    </tr>
    </tbody>
  </table>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offs/edit.html.erb
<h1>Editing off</h1>

<%= render 'form' %>

<%= button_to '削除する', @off, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/offs/index.html.erb
<h1>
  <%= link_to '<', offs_path(fy:@fy-1) %>
  <%= @fy %>
  <%= link_to '>', offs_path(fy:@fy+1)%>
</h1>
<h1 class="text-right text-margintop-50"><%= sprintf('TOTAL:%.2f', @offs.sum(:off_days)) %></h1>

<h2>休暇：<%= "%.2f"%@offs0.sum(:off_days) %></h2>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Off date</th>
    <th>Subject</th>
  </tr>
  </thead>

  <tbody>
  <% @offs0.each do |off| %>
      <tr>
        <td><%= link_to off.off_date.to_s+"（#{yo off.off_date}）", edit_off_path(off) %></td>
        <td><%= off.subject %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>半休：<%= "%.2f"%@offs1.sum(:off_days) %></h2>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Off date</th>
    <th>Subject</th>
    <th>Off half type</th>
  </tr>
  </thead>

  <tbody>
  <% @offs1.each do |off| %>
      <tr>
        <td><%= link_to off.off_date.to_s+"（#{yo off.off_date}）", edit_off_path(off) %></td>
        <td><%= off.subject %></td>
        <td><%= off.off_half_type == 1 ? '午前' : '午後' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>２時間休：<%= "%.2f"%@offs2.sum(:off_days) %></h2>
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Off date</th>
    <th>Subject</th>
    <th>Off quarter time</th>
  </tr>
  </thead>

  <tbody>
  <% @offs2.each do |off| %>
      <tr>
        <td><%= link_to off.off_date.to_s+"（#{yo off.off_date}）", edit_off_path(off) %></td>
        <td><%= off.subject %></td>
        <td><%= off.off_quarter_time.strftime('%H:%M') if off.off_quarter_time %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/offs/new.html.erb
<h1>New off</h1>

<%= render 'form' %>

app/views/offs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @off.user_id %>
</p>

<p>
  <strong>Off date:</strong>
  <%= @off.off_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @off.subject %>
</p>

<p>
  <strong>Off days:</strong>
  <%= @off.off_days %>
</p>

<p>
  <strong>Off type:</strong>
  <%= @off.off_type %>
</p>

<p>
  <strong>Off half type:</strong>
  <%= @off.off_half_type %>
</p>

<p>
  <strong>Off quarter time:</strong>
  <%= @off.off_quarter_time %>
</p>

<%= link_to 'Edit', edit_off_path(@off) %> |
<%= link_to 'Back', offs_path %>

app/views/overworks/_form.html.erb
<%= form_for(@overwork) do |f| %>
  <% if @overwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overwork.errors.count, "error") %> prohibited this overwork from being saved:</h2>

      <ul>
      <% @overwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :work_date, :value => @work_date %>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :work_start_time %><br>
    <%= f.time_select :work_start_time, minute_step: 15 %>
  </div>
  <div class="field">
    <%= f.label :work_finish_time %><br>
    <%= f.time_select :work_finish_time, minute_step: 15 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/overworks/edit.html.erb
<h1><%= @overwork.work_date.strftime('%Y/%m/%d')+"（#{yo(@overwork.work_date)}）" %></h1>

<%= render 'form' %>

<%= button_to 'Destroy', @overwork, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/overworks/index.html.erb
<h1>
  <% chevron='glyphicon glyphicon-chevron-' %>
  <%= link_to '<', overworks_path(me:@me.last_month.strftime('%Y%m'))%>
  <%= @me.strftime('%Y/%m')%>
  <%= link_to '>', overworks_path(me:@me.next_month.strftime('%Y%m'))%>
</h1>
<h1 class="text-right text-margintop-50"><%= sprintf('TOTAL:%.2f', @total) %></h1>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Subject</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Hours</th>
      <th>Comment</th>
    </tr>
  </thead>

  <tbody>
    <% (@ms..@me).each do |d| %>
      <tr <%= case d.wday; when 0; 'class=sunday' when 6; 'class=saturday'; end %>>
        <% overwork = @overworks[d] %>
        <% if overwork == nil then %>
        <td><%= link_to d.strftime('%Y/%m/%d')+"（#{yo d}）", new_overwork_path(work_date: d) %></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        <% else %>
            <td><%= link_to overwork.work_date.strftime('%Y/%m/%d')+"（#{yo d}）", edit_overwork_path(overwork) %></td>
            <td><%= overwork.subject %></td>
            <td><%= overwork.work_start_time.strftime('%H:%M') %></td>
            <td><%= overwork.work_finish_time.strftime('%H:%M') %></td>
            <td><%= sprintf( '%.2f', overwork.work_hours) %></td>
            <td><%= overwork.comment %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/overworks/new.html.erb
<h1><%= @work_date.strftime('%Y/%m/%d')+"（#{yo(@work_date)}）" %></h1>

<%= render 'form' %>

app/views/overworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @overwork.user_id %>
</p>

<p>
  <strong>Work date:</strong>
  <%= @overwork.work_date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @overwork.subject %>
</p>

<p>
  <strong>Work start time:</strong>
  <%= @overwork.work_start_time %>
</p>

<p>
  <strong>Work finish time:</strong>
  <%= @overwork.work_finish_time %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @overwork.work_hours %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @overwork.comment %>
</p>

<%= link_to 'Edit', edit_overwork_path(@overwork) %> |
<%= link_to 'Back', overworks_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>